require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable

Layout/DotPosition: { EnforcedStyle: trailing }
Layout/LineLength: { Max: 180 }

Metrics/AbcSize: { Enabled: false }
Metrics/CyclomaticComplexity: { Enabled: false }
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - "spec/**/*"
Metrics/MethodLength: { Max: 50 }
Metrics/ClassLength: { Max: 400 }
Metrics/ModuleLength: { Max: 400 }
Metrics/ParameterLists: { CountKeywordArgs: false }
Metrics/PerceivedComplexity: { Enabled: false }

Style/Documentation: { Enabled: false }
Style/GuardClause: { Enabled: false }
Style/FrozenStringLiteralComment: { Enabled: false }
Style/LambdaCall: { EnforcedStyle: braces }
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInMultilineCall: true
  AllowParenthesesInChaining: true
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%I': '()'
    '%w': '()'
    '%W': '()'

RSpec/BeforeAfterAll: { Enabled: false }
RSpec/DescribeClass: { Enabled: false }
RSpec/ExampleLength: { Enabled: false }
RSpec/InstanceVariable: { Enabled: false }
RSpec/MultipleExpectations: { Enabled: false }

