source 'https://rubygems.org'

gem 'childprocess'
gem 'cucumber'
gem 'rake'
gem 'require_all'
gem 'rspec'
gem 'rubocop', require: false
gem 'rubocop-faker'
gem 'rubocop-rspec', require: false

gemspec
